name: Workflow Filters and Activities

on:
  workflow_dispatch: 
#   schedule:
#     - cron: "*/59 * * * *"
  push:
    branches:
        - main
        - '!feature/*' #ignoring pushing to any branch name starting with feature using !
    # branch-ignore:
    #     - feature/* #feature/add/music
    #     - test/** #test/ui/index
  pull_request:
    types:
      - opened
      - closed
    paths-ignore: #workflow will only run when a pull req that includes a change on my file other than README.md
      - README.md
    branches:
      - main  #configures your workflow to only run on pull req that target specific branches

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo this workflow/job/step is executed for event type - ${{ github.event_name }}
        - 
